show databases;
CREATE database XIBM;
USE XIBM;
create table employee(EID int,ENAME varchar(150),EMAIL varchar(150));
insert into EMPLOYEE values(01,'AKSHAYA','akshaya@mail>com');
insert into EMPLOYEE (EID,ENAME,EMAIL) values(02,'STEVE ROGERS','steve@mail>com');
select * from EMPLOYEE where ENAME LIKE '%a';
insert into EMPLOYEE values(03,'Aishwarya','aishu@mail>com');
select * from EMPLOYEE where ENAME LIKE '%a';
savepoint a;
insert into EMPLOYEE values(04,'TonyStark','tonyu@mail>com');
rollback to savepoint a;
savepoint b;
insert into EMPLOYEE values(05,'Ian Somehalder','ian@mail>com');
savepoint c;
insert into EMPLOYEE values(06,'Ottery Nari','ottery@mail>com');
rollback;
select * from EMPLOYEE;
rollback to savepoint c;
rollback c;
insert into EMPLOYEE values(06,'Ottery Nari','ottery@mail>com');
insert into EMPLOYEE values(07,'Ottery Nari','ott@mail>com');
select * from EMPLOYEE;
select ENAME from EMPLOYEE group by ENAME;
select ENAME from EMPLOYEE;
create table CUSTOMERS(CNAME varchar(150),AGE INT,SALARY int,STATE varchar(150));
insert into CUSTOMERS values('AKSHAYA',18,100000,'TAMILNADU');
insert into CUSTOMERS values('STEVE ROGERS',21,1000,'KERALA');
insert into CUSTOMERS values('dHONI',22,10000,'JAMMU KASHMIR');
select STATE, count(*) AS "NUMBER OF CUSTOMERS" FROM CUSTOMERS WHERE SALARY > 10000 group by STATE;
insert into CUSTOMERS values('AISHWARYA',50,100,'TAMILNADU');
select STATE, count(*) AS "NUMBER OF CUSTOMERS" FROM CUSTOMERS WHERE SALARY > 10000 group by STATE;
insert into CUSTOMERS values('AISH',23,10000,'TAMILNADU');
select STATE, count(*) AS "NUMBER OF CUSTOMERS" FROM CUSTOMERS WHERE SALARY > 10000 group by STATE;
insert into CUSTOMERS values('STEVE',21,1000000,'KERLA');
select STATE, count(*) AS "NUMBER OF CUSTOMERS" FROM CUSTOMERS WHERE SALARY > 10000;
insert into CUSTOMERS values('AISHWARYA',50,100,'KERLA');
select STATE, count(*) AS "NUMBER OF CUSTOMERS" FROM CUSTOMERS WHERE SALARY > 10000;
select CNAME,min(SALARY) AS "lOWEST SALARY" FROM CUSTOMERS group by CNAME;
select CNAME,sum(SALARY) AS "TOTAL SALARY" from CUSTOMERS  WHERE SALARY >1000 group by CNAME;
select CNAME,sum(SALARY) AS "TOTAL SALARY" from CUSTOMERS having SALARY >1000 group by CNAME;
select CNAME,min(SALARY) AS "lOWEST SALARY" FROM CUSTOMERS group by CNAME having max(SALARY);
create table STAFF(ENAME varchar(150),AGE INT,SALARY int,STATE varchar(150));
insert into STAFF values('AISHWARYA',50,100,'TAMILNADU'); 
insert into STAFF values('AISHWARYA',50,100,'TAMILNADU'); 
create table _DATABASE(_NAME VARCHAR(150), ROLLNO INT, LOCATION VARCHAR(150),PHNO INT);
insert into _DATABASE values('RAM',101,'CHENNAI',1234738342);--
insert into _DATABASE values('RAJ',102,'COIMBATORE',1231232435);
insert into _DATABASE values('SASI',103,'MADURAI',43531342);
create table STUDENT(_NAME VARCHAR(150), ROLLNO INT, SECTION VARCHAR(150));
insert into STUDENT values('RAVI',101,'A');
insert into STUDENT values('RAJ',102,'B');
insert into STUDENT values('RAM',101,'A');
select _NAME,ROLLNO,LOCATION,PHNO FROM _DATABASE WHERE ROLLNO IN (select ROLLNO FROM STUDENT where SECTION='B');
create table EMPLOYEES(EID INT, ENAME varchar(100),DEPTID INT,AVGSAL INT);
insert into EMPLOYEES values('01','AKSHAYA',101,10000);
insert into EMPLOYEES values('02','AISHWARYA',102,20000);
insert into EMPLOYEES values('03','STEVE ROGERS',103,30000);
create table DEPARTMENT